### ISSUE TITLE
Wrong DLL path causes load failure

### ISSUE THREAD

**Issue by Kalobi** [Parrotapocalypse/ParrotHelper#1]
The assembly path in the everest.yaml for the new update (`bin/ParrotHelper.dll`) doesn't match the actual path (`bin/Debug/net7.0/ParrotHelper.dll`), causing the mod to not load.

**Comment by SquiggleCat** [comment]
Fixed! I had changed the structure and didn't remember to update that part of the `everest.yaml`.
